module.exports = {
    Badge: require('./lib/Badge'),
    Button: require('./lib/Button'),
    Card: require('./lib/Card'),
    Checkbox: require('./lib/Checkbox'),
    DataTable: require('./lib/DataTable'),
    FABButton: require('./lib/FABButton'),
    Icon: require('./lib/Icon'),
    IconButton: require('./lib/IconButton'),
    IconToggle: require('./lib/IconToggle'),
    Menu: require('./lib/Menu'),
    ProgressBar: require('./lib/ProgressBar'),
    Radio: require('./lib/Radio'),
    RadioGroup: require('./lib/RadioGroup'),
    Slider: require('./lib/Slider'),
    Spinner: require('./lib/Spinner'),
    Switch: require('./lib/Switch'),
    Textfield: require('./lib/Textfield'),
    Tooltip: require('./lib/Tooltip')
};
